version: "3.8"
networks:
  mired:
    driver: bridge  
services:
  php:
    build:
      dockerfile: php.dockerfile
    container_name: php-rc-7.3
    ports:
      - 8080:80
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db
    networks:
      - mired
  db:
    image: mysql:5.5.62
    container_name: mysql-rc
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dibu_dev_sv
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - mired
volumes:
  public: {}
  mysql_data: {}