<?php

use Laravel\Lumen\Testing\DatabaseMigrations;
use Laravel\Lumen\Testing\DatabaseTransactions;

class creacionDatos extends TestCase
{
    /**
     * Datos de la convocatoria
     *
     * @return void
     */
    public function creacionDatosConvocatoria(){
        $convocatoriaData = [
            'fecha_inicio' => '2024-03-12',
            'fecha_fin' => '2024-04-16',
            'nombre' => 'Convocatoria2024-1',
            'Convocatoria_servicio' => [
                    [
                        'servicio_id' => 1,
                        'cantidad' => 175,
                    ],
                    /*[            
                        'servicio_id' => 2,
                        'cantidad' => 240,
                    ],*/
                ],
            'secciones' => [
                'descripcion' => 'Datos Personales',
                'requisitos' => [
                    [
                        'nombre' => 'Código estudiante',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 3,
                    ],
                    [
                        'nombre' => 'DNI',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 3,
                    ],
                    [
                        'nombre' => 'Nombres',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 3,
                    ],
                    [
                        'nombre' => 'Apellidos',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 3,
                    ],
                    [
                        'nombre' => 'Sexo',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => 'M|F',
                        'tipo_requisito_id' => 4,
                    ],
                    [
                        'nombre' => 'Facultad',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 3,
                    ],
                    [
                        'nombre' => 'Escuela profesional',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 3,
                    ],
                    [
                        'nombre' => 'Modalidad de ingreso',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 3,
                    ],
                    [
                        'nombre' => 'Lugar de procedencia',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 3,
                    ],
                    [
                        'nombre' => 'Lugar de nacimiento',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 3,
                    ],
                    [
                        'nombre' => 'Edad',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 3,
                    ],
                    [
                        'nombre' => 'Correo institucional',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 3,
                    ],
                    [
                        'nombre' => 'Dirección',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 3,
                    ],
                    [
                        'nombre' => 'Fecha de nacimiento',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 3,
                    ],
                    [
                        'nombre' => 'Correo personal',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 3,
                    ],
                    [
                        'nombre' => 'Celular de estudiante',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 3,
                    ],
                    [
                        'nombre' => 'Celular padre',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 3,
                    ],
                    [
                        'nombre' => 'Tipo de estudiante',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 4,
                    ],
                ],
            ],
            [
                'descripcion' => 'Solicitan por primera vez',
                'requisitos' => [
                    [
                        'nombre' => 'Ficha socieconomica',
                        'descripcion' => 'Subir una captura de la ficha socieconomica actualizada (servicio social y pag web)',
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 2,
                    ],
                    [
                        'nombre' => 'Seleccion su clasificación según su SISFOH vigente',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 4,
                    ],
                    [
                        'nombre' => 'Suba la captura de su SISFOH vigente',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 2,
                    ],
                    [
                        'nombre' => 'Copia de DNI de los padres',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 1,
                    ],
                    [
                        'nombre' => 'Copia de DNI del solicitante',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 1,
                    ],
                    [
                        'nombre' => 'Una (01) fotorafia actualizada tamaño carnet y/o pasaporte',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 1,
                    ],
                ],
            ],
            [
                'descripcion' => 'Documentos solicitados',
                'requisitos' => [
                    [
                        'nombre' => 'Carta de compromiso de los padres para uso de los servicios solicitados (Menores de edad)',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 1,
                    ],
                    [
                        'nombre' => 'Solicitud dirigida a la dirección de bienestar universitario',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 2,
                    ],
                    [
                        'nombre' => 'Copia de recivo de luz y/o agua los que solicitan por primera vez',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 2,
                    ],
                    [
                        'nombre' => 'Reporte de deudas de tesoreria',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 2,
                    ],
                    [
                        'nombre' => 'Formato de atencion de los servicios de DBU',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 2,
                    ],
                    [
                        'nombre' => 'Certijoven policiales',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 4,
                    ],
                    [
                        'nombre' => 'Certijoven judiciales',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 4,
                    ],
                    [
                        'nombre' => 'Certijoven penales',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 4,
                    ],
                    [
                        'nombre' => 'Certificado actualizado unico laboral CERTIJOVEN (Pag web del Ministerio de Trabajo)',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 2,
                    ],
                    [
                        'nombre' => 'Carne de vacuna antitetanica',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 2,
                    ],
                    [
                        'nombre' => 'Carne de vacuna antihepatitis',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 2,
                    ],
                    [
                        'nombre' => 'Seguro de salud',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 4,
                    ],
                    [
                        'nombre' => 'Constancia vigente del SIS o seguro particular',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 2,
                    ],
                    [
                        'nombre' => 'Carta de compromiso para la asistencia a los talleres de psicopedagogia minimo 03 veces',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 1,
                    ],
                    [
                        'nombre' => 'Certificado domiciliario',
                        'descripcion' => null,
                        'url_guia' => null,
                        'url_plantilla' => null,
                        'opciones' => null,
                        'tipo_requisito_id' => 2,
                    ],
                ],
            ],
        ];
        return $convocatoriaData;
    }
}
